apiVersion: datadog-in-crossplane.legalzoom.com/v1alpha1
kind: XBasicObservabilityBundle
metadata:
  name: basic-observability-bundle-for-test-service
spec:
  serviceName: cartservice
  targetThreshold: 90
  warningThreshold: 99
