# https://github.com/upbound/provider-datadog
# https://doc.crds.dev/github.com/upbound/provider-datadog
apiVersion: datadog.upbound.io/v1alpha1
kind: Team
metadata:
  name: jackjack-test-crossplane-team
spec:
  forProvider:
    name: jackjack-test-team
    handle: jackjack-test-team-handle
    description: "Hello! This was created with Crossplane"
---
# Adapted from https://github.legalzoom.com/engineering/authorization-service-deployment/blob/master/envs/prd/monitoring.yaml
# but translated into Crossplane-language
apiVersion: datadog.upbound.io/v1alpha1
kind: Monitor
metadata:
  name: basic-monitor
spec:
  forProvider:
    name: jackjack-example-monitor
    query: "sum(last_4h):anomalies(sum:authorization.login_success_total{*}.as_count(), 'agile', 3, direction='both', interval=60, alert_window='last_5m', timezone='America/Los_Angeles', count_default_zero='true', seasonality='weekly') >= 1"
    type: "query alert"
    message: "@pagerduty-fake_name_to_not_page_anyone"
    tags:
      - "sre"
    priority: null
    evaluationDelay: 60
    includeTags: true
    notifyNoData: true
    noDataTimeframe: 300
    renotifyInterval: 0
    monitorThresholdWindows:
      - recoveryWindow: last_5m
        triggerWindow: last_5m
    monitorThresholds:
      - critical: "1"
        criticalRecovery: "0"
---
# None listed here: https://github.legalzoom.com/engineering/authorization-service-deployment/blob/master/envs/prd/monitoring.yaml
# So I pulled from an existing specification here:
# https://app.datadoghq.com/slo/manage?slo_id=58b620da2be95510a51f828f56011163&tab=status_and_history&from_ts=1708213490360&to_ts=1710805490360&paused=false
# and changed appropriate values to avoid making folks think this is a "real" SLO
#
# (Fetch the base info with:
# `$ curl -H "DD-APPLICATION-KEY: <...>" -H "DD-API-KEY: <...>" https://api.datadoghq.com/api/v1/slo/58b620da2be95510a51f828f56011163)
apiVersion: datadog.upbound.io/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: jackjack-basic-slo
spec:
  forProvider:
    name: jackjack-example-slo-for-api-cart-service
    thresholds:
      - timeframe: 30d
        target: 98.0
        warning: 99.0
    type: "metric"
    description: "A copy of SLO ID 58b620da2be95510a51f828f56011163"
    timeframe: "30d"
    targetThreshold: 98.0
    warningThreshold: 99.0
    query:
      - denominator: "sum:trace.opentelemetry.server.hits.by_http_status{env:p,service:api-cart-service.api-cart-service-usw2-prd}.as_count()"
        numerator: "sum:trace.opentelemetry.server.hits.by_http_status{env:p,service:api-cart-service.api-cart-service-usw2-prd}.as_count() - sum:trace.opentelemetry.server.hits.by_http_status{env:p,service:api-cart-service.api-cart-service-usw2-prd,http.status_code:400}.as_count()"
---
# Taken from ...
apiVersion: datadog.upbound.io/v1alpha1
kind: DashboardJSON
metadata:
  name: jackjack-basic-dashboard
spec:
  forProvider:
    dashboard: |
      {
        "title": "jackjack-basic-dashboard",
        "description": "",
        "widgets": [
            {
                "id": 7517335659303630,
                "definition": {
                    "title": "Log series for Advisor Configuration Service",
                    "title_size": "16",
                    "title_align": "left",
                    "show_legend": true,
                    "legend_layout": "auto",
                    "legend_columns": [
                        "avg",
                        "min",
                        "max",
                        "value",
                        "sum"
                    ],
                    "type": "timeseries",
                    "requests": [
                        {
                            "formulas": [
                                {
                                    "formula": "query1"
                                }
                            ],
                            "queries": [
                                {
                                    "data_source": "logs",
                                    "name": "query1",
                                    "search": {
                                        "query": "service:AdvisorConfigurationService"
                                    },
                                    "indexes": [
                                        "*"
                                    ],
                                    "compute": {
                                        "aggregation": "count"
                                    },
                                    "group_by": [],
                                    "storage": "hot"
                                }
                            ],
                            "response_format": "timeseries",
                            "style": {
                                "palette": "dog_classic",
                                "line_type": "solid",
                                "line_width": "normal"
                            },
                            "display_type": "line"
                        }
                    ]
                },
                "layout": {
                    "x": 0,
                    "y": 0,
                    "width": 6,
                    "height": 4
                }
            },
            {
                "id": 4998496327427478,
                "definition": {
                    "title": "Error for AdvisorConfigurationService",
                    "title_size": "16",
                    "title_align": "left",
                    "show_legend": true,
                    "legend_layout": "auto",
                    "legend_columns": [
                        "avg",
                        "min",
                        "max",
                        "value",
                        "sum"
                    ],
                    "type": "timeseries",
                    "requests": [
                        {
                            "formulas": [
                                {
                                    "formula": "query1"
                                }
                            ],
                            "queries": [
                                {
                                    "data_source": "events",
                                    "name": "query1",
                                    "search": {
                                        "query": "service:AdvisorConfigurationService status:error"
                                    },
                                    "indexes": [
                                        "*"
                                    ],
                                    "compute": {
                                        "aggregation": "count"
                                    },
                                    "group_by": []
                                }
                            ],
                            "response_format": "timeseries",
                            "style": {
                                "palette": "dog_classic",
                                "line_type": "solid",
                                "line_width": "normal"
                            },
                            "display_type": "line"
                        }
                    ]
                },
                "layout": {
                    "x": 6,
                    "y": 0,
                    "width": 6,
                    "height": 4
                }
            },
            {
                "id": 1056546795936528,
                "definition": {
                    "title": "Logs",
                    "title_size": "16",
                    "title_align": "left",
                    "requests": [
                        {
                            "response_format": "event_list",
                            "columns": [
                                {
                                    "field": "status_line",
                                    "width": "auto"
                                },
                                {
                                    "field": "timestamp",
                                    "width": "auto"
                                },
                                {
                                    "field": "host",
                                    "width": "auto"
                                },
                                {
                                    "field": "service",
                                    "width": "auto"
                                },
                                {
                                    "field": "content",
                                    "width": "compact"
                                }
                            ],
                            "query": {
                                "data_source": "logs_stream",
                                "query_string": "service:AdvisorConfigurationService",
                                "indexes": [],
                                "storage": "hot"
                            }
                        }
                    ],
                    "type": "list_stream"
                },
                "layout": {
                    "x": 0,
                    "y": 4,
                    "width": 12,
                    "height": 4
                }
            }
        ],
        "template_variables": [],
        "layout_type": "ordered",
        "notify_list": [],
        "reflow_type": "fixed",
        "tags": []
      }
