apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datadog-in-crossplane-demo-application
  name: datadog-in-crossplane-demo-application
  namespace: datadog-in-crossplane-demo-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-in-crossplane-demo-application
  template:
    metadata:
      labels:
        app: datadog-in-crossplane-demo-application
    spec:
      containers:
        - name: main-container
          image: busybox
          command: ['/bin/sh', '-c']
          args:
            - |
              while true
              do
                echo "Hello World!"
                sleep 5
              done
